"""Add IMAP support fields to User

Revision ID: 53c7c278e41d
Revises: 2d4401195144
Create Date: 2025-06-22 14:54:10.621792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c7c278e41d'
down_revision: Union[str, None] = '2d4401195144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Add columns with temporary default values for existing rows
    op.add_column('users', sa.Column('email_address', sa.String(), nullable=False, server_default='temp@example.com'))
    op.add_column('users', sa.Column('imap_password_encrypted', sa.String(), nullable=False, server_default='PLACEHOLDER'))

    # OPTIONAL: Remove server defaults so they don’t apply to future inserts
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('email_address', server_default=None)
        batch_op.alter_column('imap_password_encrypted', server_default=None)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'imap_password_encrypted')
    op.drop_column('users', 'email_address')
    # ### end Alembic commands ###
