"""Add priority to EmailStatus

Revision ID: 5c5f0cd67d9f
Revises: 53c7c278e41d
Create Date: 2025-06-23 15:37:27.299888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5f0cd67d9f'
down_revision: Union[str, None] = '53c7c278e41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
