"""Add priority column to EmailStatus

Revision ID: ad53480f144a
Revises: bd2be8ec1bf0
Create Date: 2025-06-23 15:54:37.052034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad53480f144a'
down_revision: Union[str, None] = 'bd2be8ec1bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_status', sa.Column('priority', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_status', 'priority')
    # ### end Alembic commands ###
