"""Add priority to EmailStatus

Revision ID: bd2be8ec1bf0
Revises: 5c5f0cd67d9f
Create Date: 2025-06-23 15:39:14.629681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2be8ec1bf0'
down_revision: Union[str, None] = '5c5f0cd67d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
